### ISSUE TITLE
Plugin does not work with resized images?

### ISSUE THREAD

**Issue by Orrico** [wmh/jquery-scrollbox#12]
Hi,

I'm trying to install the plugin but it doesn't work with resized images for thumbnails. My code:

CSS

``` css
.scroll-img {
    border: 1px solid red;
    width: 100%;
    height: 142px;
    overflow: hidden;
  }
  .scroll-img ul {
    width: 100%;
    height: 600px;
    margin: 0;
  }
  .scroll-img ul li {
    display: inline-block;
    margin: 10px 0 10px 10px;
  }
  .galeria-img {
    width: 160px;
    height: 120px;
  }
  .galeria-control {
    text-align: center;
  }
  .galeria-control span {
    color: white;
    font-size: 18px;
    background: #ccc;
    border-radius: 15px;
    padding: 5px;
    cursor: pointer;
  }
```

JavaScript

``` javascript
$('#galeria').scrollbox({
    direction: 'h',
    distance: 160
  });

  $('.prev-item').click(function () {
    $('#galeria').trigger('backward');
  });

  $('.next-item').click(function () {
    $('#galeria').trigger('forward');
  });

  });
```

HTML

``` html
<div id="galeria" class="scroll-img">
    <ul>
        <li class="galeria-item">
          <a href="img/galeria/image" title="">
            <img class="galeria-img" src="img/galeria/image" title="">
          </a>
        </li>
        <li>
          ...
        </li>
        ...
    </ul>
  </div>
  <div class="galeria-control">
    <span class="prev-item">&larr; Prev</span>
    <span class="next-item">Next &rarr;</span>
  </div>
```

How i can use a image without cropping it, only resize it? Because i use a modal plugin (Magnific-popup) to open the bigger image.
