### ISSUE TITLE
Demo 5 does not scroll smoothly as in demo version

### ISSUE THREAD

**Issue by wilkesvb** [wmh/jquery-scrollbox#22]
See: http://codepen.io/wilkesvb/pen/WbORGX

**Comment by wmh** [comment]
ul requires a width bigger than it's parent
```css
ul {
    display: inline-block;
    width: 900px;
  }
```
distance 1 is incorrect, remove it
```js
$('#demo5').scrollbox({
  direction: 'h'
});
```
